version: '3.7'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    depends_on:
      - app
      - api

  app:
    container_name: frontend-flutterfly
    build: ./
    working_dir: /usr/src/flutterfly
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/flutterfly

  api:
    container_name: backend-flutterfly
    build: ./server
    command: npm run start-watch
    working_dir: /usr/src/flutterfly-backend
    environment:
      AMADEUS_CLIENT_ID: 'your AMADEUS_CLIENT_ID'
      AMADEUS_CLIENT_SECRET: 'your AMADEUS_CLIENT_SECRET'
      GOOGLE_API_KEY: 'your GOOGLE_API_KEY'
      NODE_ENV: 'development'
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./server/:/usr/src/flutterfly-backend
